// Recovery Hook Template
// Auto-generated by meta-improver

export default async function recovery{{tool}}(context: any) {
  const { toolResult, attempt, maxAttempts = 3 } = context;
  
  if (!toolResult?.success && attempt < maxAttempts) {
    console.log(`[Recovery] {{tool}} attempt ${attempt + 1}/${maxAttempts}`);
    
    return {
      shouldRetry: true,
      delay: Math.min(1000 * Math.pow(2, attempt), 30000),
      modifiedInput: null
    };
  }
  
  if (!toolResult?.success) {
    return {
      shouldRetry: false,
      fallback: true,
      alternativeApproach: 'Consider using a different tool or simplifying the request'
    };
  }
  
  return { shouldRetry: false };
}
